//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.09 at 10:38:21 AM CET 
//


package it.nerdammer.seasurf.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sea-surf-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sea-surf-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="security-token" type="{http://www.nerdammer.it/sea-surf-config_1_0}security-token" minOccurs="0"/>
 *         &lt;element name="referer-constraints" type="{http://www.nerdammer.it/sea-surf-config_1_0}referer-constraints" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sea-surf-config", propOrder = {
    "securityToken",
    "refererConstraints"
})
public class SeaSurfConfig {

    @XmlElement(name = "security-token")
    protected SecurityToken securityToken;
    @XmlElement(name = "referer-constraints")
    protected RefererConstraints refererConstraints;

    /**
     * Gets the value of the securityToken property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityToken }
     *     
     */
    public SecurityToken getSecurityToken() {
        return securityToken;
    }

    /**
     * Sets the value of the securityToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityToken }
     *     
     */
    public void setSecurityToken(SecurityToken value) {
        this.securityToken = value;
    }

    /**
     * Gets the value of the refererConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link RefererConstraints }
     *     
     */
    public RefererConstraints getRefererConstraints() {
        return refererConstraints;
    }

    /**
     * Sets the value of the refererConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefererConstraints }
     *     
     */
    public void setRefererConstraints(RefererConstraints value) {
        this.refererConstraints = value;
    }

}
