//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 02:30:15 AM CET 
//


package it.nerdammer.seasurf.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sea-surf-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sea-surf-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="security-token-constraints" type="{http://www.nerdammer.it/sea-surf-config_1_0}security-token-constraints" minOccurs="0"/>
 *         &lt;element name="referer-constraints" type="{http://www.nerdammer.it/sea-surf-config_1_0}referer-constraints" minOccurs="0"/>
 *         &lt;element name="preferences" type="{http://www.nerdammer.it/sea-surf-config_1_0}preferences" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sea-surf-config", propOrder = {
    "securityTokenConstraints",
    "refererConstraints",
    "preferences"
})
public class SeaSurfConfig {

    @XmlElement(name = "security-token-constraints")
    protected SecurityTokenConstraints securityTokenConstraints;
    @XmlElement(name = "referer-constraints")
    protected RefererConstraints refererConstraints;
    protected Preferences preferences;

    /**
     * Gets the value of the securityTokenConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityTokenConstraints }
     *     
     */
    public SecurityTokenConstraints getSecurityTokenConstraints() {
        return securityTokenConstraints;
    }

    /**
     * Sets the value of the securityTokenConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityTokenConstraints }
     *     
     */
    public void setSecurityTokenConstraints(SecurityTokenConstraints value) {
        this.securityTokenConstraints = value;
    }

    /**
     * Gets the value of the refererConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link RefererConstraints }
     *     
     */
    public RefererConstraints getRefererConstraints() {
        return refererConstraints;
    }

    /**
     * Sets the value of the refererConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefererConstraints }
     *     
     */
    public void setRefererConstraints(RefererConstraints value) {
        this.refererConstraints = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link Preferences }
     *     
     */
    public Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preferences }
     *     
     */
    public void setPreferences(Preferences value) {
        this.preferences = value;
    }

}
