//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 10:31:10 PM CET 
//


package it.nerdammer.seasurf.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for preferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="preferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="token-length" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="12"/>
 *               &lt;maxInclusive value="50"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="18"/>
 *               &lt;enumeration value="20"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="26"/>
 *               &lt;enumeration value="28"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="32"/>
 *               &lt;enumeration value="34"/>
 *               &lt;enumeration value="36"/>
 *               &lt;enumeration value="38"/>
 *               &lt;enumeration value="40"/>
 *               &lt;enumeration value="42"/>
 *               &lt;enumeration value="44"/>
 *               &lt;enumeration value="46"/>
 *               &lt;enumeration value="48"/>
 *               &lt;enumeration value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="token-parameter-name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="token-storage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SESSION"/>
 *               &lt;enumeration value="COOKIE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="token-name-on-storage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "preferences", propOrder = {

})
public class Preferences {

    @XmlElement(name = "token-length")
    protected Integer tokenLength;
    @XmlElement(name = "token-parameter-name")
    protected String tokenParameterName;
    @XmlElement(name = "token-storage")
    protected String tokenStorage;
    @XmlElement(name = "token-name-on-storage")
    protected String tokenNameOnStorage;

    /**
     * Gets the value of the tokenLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTokenLength() {
        return tokenLength;
    }

    /**
     * Sets the value of the tokenLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTokenLength(Integer value) {
        this.tokenLength = value;
    }

    /**
     * Gets the value of the tokenParameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenParameterName() {
        return tokenParameterName;
    }

    /**
     * Sets the value of the tokenParameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenParameterName(String value) {
        this.tokenParameterName = value;
    }

    /**
     * Gets the value of the tokenStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenStorage() {
        return tokenStorage;
    }

    /**
     * Sets the value of the tokenStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenStorage(String value) {
        this.tokenStorage = value;
    }

    /**
     * Gets the value of the tokenNameOnStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenNameOnStorage() {
        return tokenNameOnStorage;
    }

    /**
     * Sets the value of the tokenNameOnStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenNameOnStorage(String value) {
        this.tokenNameOnStorage = value;
    }

}
